CREATE TABLE IF NOT EXISTS meeting_invitation (
  INVITE_ID            CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  MEETING_TITLE        VARCHAR(255) NOT NULL,
  MEETING_DATE         DATE NULL,
  MEETING_TIME         TIME NULL,
  RECIPIENT_EMAIL      VARCHAR(254) NOT NULL,
  RECIPIENT_OBJECT_ID  CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  TENANT_ID            CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  TOKEN_HASH           CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  CALENDAR_UID         VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  RESPONSE_STATUS      ENUM('PENDING','YES','NO','MAYBE') NOT NULL DEFAULT 'PENDING',
  CREATED_BY           VARCHAR(100) NULL,
  EMAIL_MESSAGE_ID     VARCHAR(255) NULL,
  CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  EXPIRES_AT           DATETIME NOT NULL,
  RESPONDED_AT         DATETIME NULL,

  PRIMARY KEY (INVITE_ID),
  UNIQUE KEY UK_MEETING_INVITATION_TOKEN (TOKEN_HASH),
  UNIQUE KEY UK_MEETING_INVITATION_CALENDAR (CALENDAR_UID),
  KEY IX_MEETING_INVITATION_RECIPIENT (RECIPIENT_EMAIL, CREATED_AT),
  KEY IX_MEETING_INVITATION_STATUS (RESPONSE_STATUS, EXPIRES_AT)
) ENGINE=InnoDB;
