ALTER TABLE meeting_invitation
  MODIFY TENANT_ID CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  ADD COLUMN CALENDAR_UID VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NULL AFTER TOKEN_HASH;

UPDATE meeting_invitation
   SET CALENDAR_UID = CONCAT(INVITE_ID, '@legacy.local')
 WHERE CALENDAR_UID IS NULL;

ALTER TABLE meeting_invitation
  MODIFY CALENDAR_UID VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  ADD UNIQUE KEY UK_MEETING_INVITATION_CALENDAR (CALENDAR_UID);

