-- Apply this once to an existing Employee Portal V5 database.
-- Existing employees remain usable; new submissions are explicitly created as PENDING.
ALTER TABLE UP_EMP
  ADD COLUMN APPROVAL_STATUS ENUM('PENDING','APPROVED','REJECTED')
    NOT NULL DEFAULT 'APPROVED' AFTER IPI,
  ADD COLUMN APPROVED_BY VARCHAR(100) NULL AFTER APPROVAL_STATUS,
  ADD COLUMN APPROVED_AT DATETIME NULL AFTER APPROVED_BY,
  ADD KEY IX_UP_EMP_APPROVAL (APPROVAL_STATUS);
