-- Run once on an existing MySQL/Aiven database before deploying child entry.
-- EMP_ENTRY_ID keeps draft child rows linked before an IPI is assigned.

CREATE TABLE IF NOT EXISTS hr_empfamilydet (
  FAMILY_ID     BIGINT NOT NULL AUTO_INCREMENT,
  EMP_ENTRY_ID  BIGINT NOT NULL,
  EMPCODE       VARCHAR(50) NULL,
  FNAME         VARCHAR(100) NULL,
  F_OCUP        VARCHAR(70) NULL,
  F_ADD         VARCHAR(100) NULL,
  PHONE         VARCHAR(25) NULL,
  CHILD_NOS     INT NOT NULL,
  BIRTH_DATE    DATE NULL,
  PRIMARY KEY (FAMILY_ID),
  UNIQUE KEY UK_FAMILY_ENTRY_CHILD (EMP_ENTRY_ID, CHILD_NOS),
  KEY IX_FAMILY_EMPCODE (EMPCODE),
  CONSTRAINT FK_FAMILY_EMP_ENTRY
    FOREIGN KEY (EMP_ENTRY_ID) REFERENCES up_emp(EMP_ENTRY_ID)
    ON DELETE CASCADE
) ENGINE=InnoDB;
