-- Run while logged in to the Oracle schema that owns the existing tables.
-- These read-only queries show the columns and keys needed for the mapping.
SELECT TABLE_NAME, COLUMN_ID, COLUMN_NAME, DATA_TYPE,
       DATA_LENGTH, CHAR_LENGTH, CHAR_USED, DATA_PRECISION, DATA_SCALE,
       NULLABLE, DATA_DEFAULT, IDENTITY_COLUMN
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME IN ('UP_EMP', 'HR_EMPEXAMDET', 'HR_EMPFAMILYDET')
 ORDER BY TABLE_NAME, COLUMN_ID;

SELECT c.TABLE_NAME, c.CONSTRAINT_NAME, c.CONSTRAINT_TYPE, c.STATUS,
       c.VALIDATED, cc.POSITION, cc.COLUMN_NAME
  FROM USER_CONSTRAINTS c
  JOIN USER_CONS_COLUMNS cc
    ON cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME
   AND cc.TABLE_NAME = c.TABLE_NAME
 WHERE c.TABLE_NAME IN ('UP_EMP', 'HR_EMPEXAMDET', 'HR_EMPFAMILYDET')
   AND c.CONSTRAINT_TYPE IN ('P', 'U', 'R')
 ORDER BY c.TABLE_NAME, c.CONSTRAINT_NAME, cc.POSITION;
