CREATE DATABASE IF NOT EXISTS employee_portal
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE employee_portal;

CREATE TABLE HR_BATCH_CONTROL (
  BATCH_NO      VARCHAR(100) NOT NULL,
  STATUS        ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'INACTIVE',
  STARTED_AT    DATETIME NULL,
  CLOSED_AT     DATETIME NULL,
  CREATED_BY    VARCHAR(150) NULL,
  CREATED_AT    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (BATCH_NO),
  KEY IX_BATCH_STATUS (STATUS)
) ENGINE=InnoDB;

CREATE TABLE UP_EMP (
  EMP_ENTRY_ID           BIGINT NOT NULL AUTO_INCREMENT,

  -- Employee first identifies himself using these values.
  MERITLIST_ID           VARCHAR(100) NOT NULL,
  CLASS_ID               VARCHAR(100) NOT NULL,

  -- Admin assigns IPI later.
  IPI                    VARCHAR(50) NULL,

  NAME                   VARCHAR(1000),
  batch_no               VARCHAR(100) NOT NULL,
  BIRTHDATE              DATE,
  BLD_GROUP              VARCHAR(30),
  GENDER                 CHAR(1),
  RELIGION               CHAR(1),
  NATIONALITY            VARCHAR(50),
  MARITAL_STATUS         CHAR(1),
  EMAIL                  VARCHAR(300),
  PHONE                  VARCHAR(30) NOT NULL,
  PHONE1                 VARCHAR(50),
  HEIGHT                 VARCHAR(300),
  WEIGHT                 VARCHAR(300),
  NID                    VARCHAR(30),
  PERMANENT_VILLAGE      VARCHAR(300),
  PERMANENT_POST         VARCHAR(300),
  PERMANENT_THANA        VARCHAR(300),
  PERMANENT_DISTRICT     VARCHAR(300),
  PRESENT_VILLAGE        VARCHAR(300),
  PRESENT_POST           VARCHAR(300),
  PRESENT_THANA          VARCHAR(300),
  PRESENT_DISTRICT       VARCHAR(300),
  EMGRCNY_PERSON         VARCHAR(300),
  EMGRCNY_RELATION       VARCHAR(50),
  EMGRCNY_ADDRESS        VARCHAR(255),
  EMGRCNY_PHONE          VARCHAR(20),
  FATHER_NAME            VARCHAR(300),
  FATHER_PHONE           VARCHAR(20),
  MOTHER_NAME            VARCHAR(300),
  MOTHER_PHONE           VARCHAR(20),
  SPOUSE_NAME            VARCHAR(300),
  SPOSE_MARRIAGE_DATE    DATE,
  SPOSE_OCCUPATION       VARCHAR(300),
  SPOUSE_PHONE           VARCHAR(30),
  GRNT_NAME              VARCHAR(300),
  GRNT_RELE              VARCHAR(100),
  GRNT_FATHER            VARCHAR(300),
  GRNT_PRESENT_ADD       VARCHAR(255),
  GRNT_PERMANET_ADD      VARCHAR(255),
  GRNT_NATIONALITY       VARCHAR(50),
  GRNT_PROFFESSION       VARCHAR(300),
  GRNT_NID               VARCHAR(30),
  GRNT_MOBILE            VARCHAR(20),
  CREATED_AT             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT             DATETIME NULL,

  PRIMARY KEY (EMP_ENTRY_ID),
  UNIQUE KEY UK_EMP_MERIT_CLASS (MERITLIST_ID, CLASS_ID),
  UNIQUE KEY UK_EMP_IPI (IPI),
  KEY IX_UP_EMP_BATCH (batch_no),
  KEY IX_EMP_VERIFY (MERITLIST_ID, CLASS_ID, PHONE),
  CONSTRAINT FK_UP_EMP_BATCH
    FOREIGN KEY (batch_no) REFERENCES HR_BATCH_CONTROL(BATCH_NO)
) ENGINE=InnoDB;

CREATE TABLE HR_EMPEXAMDET (
  SLNO          BIGINT NOT NULL AUTO_INCREMENT,

  -- Internal relational key; always available even before IPI assignment.
  EMP_ENTRY_ID  BIGINT NOT NULL,

  -- Oracle-facing employee code. Null until admin assigns IPI.
  EMPCODE       VARCHAR(50) NULL,

  EXAMNAME      VARCHAR(170),
  EXAMGROUP     VARCHAR(170),
  BOARD         VARCHAR(1000),
  CLAS          VARCHAR(300),
  PASSYEAR      VARCHAR(100),
  REMARKS       VARCHAR(100),
  INSTITUTE     VARCHAR(500),
  SUBJECT_NAME VARCHAR(200),

  PRIMARY KEY (SLNO),
  KEY IX_EXAM_ENTRY (EMP_ENTRY_ID),
  KEY IX_EXAM_EMPCODE (EMPCODE),

  CONSTRAINT FK_EXAM_EMP_ENTRY
    FOREIGN KEY (EMP_ENTRY_ID) REFERENCES UP_EMP(EMP_ENTRY_ID)
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE HR_UPDATE_REQUEST (
  REQUEST_ID       CHAR(36) NOT NULL,
  EMP_ENTRY_ID     BIGINT NOT NULL,
  IPI              VARCHAR(50) NULL,
  MERITLIST_ID     VARCHAR(100) NOT NULL,
  CLASS_ID         VARCHAR(100) NOT NULL,
  BATCH_NO         VARCHAR(100) NOT NULL,
  REQUEST_NOTE     VARCHAR(1000),
  REQUESTED_AT     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  STATUS           ENUM('PENDING','APPROVED','REJECTED','EXPIRED') NOT NULL DEFAULT 'PENDING',
  APPROVED_AT      DATETIME NULL,
  APPROVED_UNTIL   DATETIME NULL,
  APPROVED_BY      VARCHAR(150) NULL,
  ADMIN_REMARKS    VARCHAR(1000) NULL,
  UPDATED_AT       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (REQUEST_ID),
  KEY IX_REQ_ENTRY_STATUS (EMP_ENTRY_ID, STATUS),
  KEY IX_REQ_APPROVED_UNTIL (APPROVED_UNTIL),

  CONSTRAINT FK_REQ_EMP_ENTRY
    FOREIGN KEY (EMP_ENTRY_ID) REFERENCES UP_EMP(EMP_ENTRY_ID),
  CONSTRAINT FK_REQ_BATCH
    FOREIGN KEY (BATCH_NO) REFERENCES HR_BATCH_CONTROL(BATCH_NO)
) ENGINE=InnoDB;

CREATE TABLE ADMIN_USER (
  USER_ID        BIGINT NOT NULL AUTO_INCREMENT,
  USERNAME       VARCHAR(100) NOT NULL,
  PASSWORD_HASH  VARCHAR(255) NOT NULL,
  DISPLAY_NAME   VARCHAR(200),
  ACTIVE_YN      CHAR(1) NOT NULL DEFAULT 'Y',
  CREATED_AT     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (USER_ID),
  UNIQUE KEY UK_ADMIN_USERNAME (USERNAME)
) ENGINE=InnoDB;
